name = "CJieba"
uuid = "ed619804-44bc-4c56-bdd2-11e3a27b3f1e"
authors = ["Alex Zheng"]
version = "0.1.0"

[deps]
CJieba_jll = "a2ce7b33-90ba-591a-b03f-46764c5db586"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
